<?php

/*
 * Brand-published notes checked on 2026-10-01. These are olfactory notes, not
 * ingredient lists. Mood, story and occasion copy is Soopi's editorial advice.
 * Only use a pyramid when the cited brand explicitly identifies its layers.
 * Missing products intentionally remain unclassified; never infer from an ID.
 */
return [
    'reviewed_at' => '2026-10-01',
    'profiles' => [
        'sauvage-edp' => [
            'names' => ['Dior Sauvage', 'Dior Sauvage Eau de Parfum', 'Sauvage Eau de Parfum'],
            'slugs' => ['dior-sauvage', 'dior-sauvage-eau-de-parfum', 'sauvage-eau-de-parfum'],
            'brands' => ['Dior', 'Christian Dior'],
            'concentrations' => ['edp'],
            'mode' => 'pyramid',
            'family' => 'Cam chanh · Gia vị · Vanilla',
            'layers' => [
                'top' => ['label' => 'Hương đầu', 'notes' => ['Bergamot Calabria'], 'description' => 'Sắc cam chanh tươi, sáng và hơi cay.'],
                'heart' => ['label' => 'Hương giữa', 'notes' => ['Tiêu Tứ Xuyên', 'Oải hương', 'Hoa hồi'], 'description' => 'Thảo mộc gặp gia vị, tạo điểm chuyển ấm.'],
                'base' => ['label' => 'Hương cuối', 'notes' => ['Vanilla Papua New Guinea', 'Ambroxan'], 'description' => 'Dư âm vanilla ấm cùng sắc hương hơi khói.'],
            ],
            'key_notes' => ['Bergamot Calabria', 'Oải hương', 'Vanilla', 'Ambroxan'],
            'moods' => ['sage', 'velvet'],
            'mood_reason' => ['sage' => 'Bergamot đem lại điểm mở đầu tươi sáng.', 'velvet' => 'Vanilla và gia vị tạo chiều sâu ấm áp.'],
            'story' => 'Cam chanh bừng sáng rồi nhường chỗ cho gia vị và vanilla. Một tương phản giữa nét tươi và nền ấm.',
            'occasion' => 'Gợi ý Soopi: thử cho một buổi gặp gỡ hoặc buổi tối; điều chỉnh lượng xịt theo không gian.',
            'sources' => [['label' => 'Dior — Sauvage Eau de Parfum', 'url' => 'https://www.dior.com/en_us/beauty/products/sauvage-eau-de-parfum-Y0785220.html']],
        ],
        'miss-dior-blooming-bouquet-edt' => [
            'names' => ['Miss Dior Blooming Bouquet EDT', 'Miss Dior Blooming Bouquet', 'Miss Dior Blooming Bouquet Eau de Toilette'],
            'slugs' => ['miss-dior-blooming-bouquet', 'miss-dior-blooming-bouquet-edt', 'miss-dior-blooming-bouquet-eau-de-toilette'],
            'brands' => ['Dior', 'Christian Dior'],
            'concentrations' => ['edt'],
            'mode' => 'keynotes',
            'family' => 'Hoa cỏ · Xạ hương',
            'key_notes' => ['Bergamot', 'Hoa hồng Damascus', 'Mẫu đơn', 'Xạ hương trắng'],
            'moods' => ['rose', 'sage'],
            'mood_reason' => ['rose' => 'Mẫu đơn và xạ hương trắng gợi cảm giác mềm mại.', 'sage' => 'Bergamot điểm nét tươi lên bó hoa nhẹ nhàng.'],
            'story' => 'Mẫu đơn và hoa hồng gặp sắc tươi của bergamot, được xạ hương trắng làm mềm. Một bó hoa thoáng nhẹ để gần gũi hơn.',
            'occasion' => 'Gợi ý Soopi: thử cho ban ngày, đi làm hoặc một buổi hẹn nhẹ nhàng.',
            'sources' => [['label' => 'Dior — Miss Dior Blooming Bouquet', 'url' => 'https://www.dior.com/en_us/beauty/products/miss-dior-blooming-bouquet-Y0996612.html']],
        ],
        'chance-eau-tendre-edp' => [
            'names' => ['Chanel Chance Eau Tendre EDP', 'Chanel Chance Eau Tendre Eau de Parfum', 'Chance Eau Tendre Eau de Parfum'],
            'slugs' => ['chanel-chance-eau-tendre', 'chanel-chance-eau-tendre-edp', 'chance-eau-tendre-eau-de-parfum'],
            'brands' => ['Chanel'],
            'concentrations' => ['edp'],
            'mode' => 'keynotes',
            'family' => 'Hoa cỏ',
            'key_notes' => ['Hoa nhài absolute', 'Tinh chất hoa hồng'],
            'moods' => ['rose'],
            'mood_reason' => ['rose' => 'Hoa nhài và hoa hồng tạo dấu hương mềm, ôm nhẹ.'],
            'story' => 'Hoa nhài và hoa hồng cùng tỏa sáng trong một nét hương mềm mại. Sự dịu dàng ở đây có độ đầy đặn và rõ nét.',
            'occasion' => 'Gợi ý Soopi: thử cho ngày muốn một dấu hương hoa thanh lịch, từ công việc đến buổi hẹn.',
            'sources' => [['label' => 'Chanel — Chance Eau Tendre Eau de Parfum', 'url' => 'https://www.chanel.com/us/fragrance/p/126270/chance-eau-tendre-eau-de-parfum-spray/']],
        ],
        'delina-exclusif' => [
            'names' => ['Parfums de Marly Delina Exclusif', 'Delina Exclusif'],
            'slugs' => ['parfums-de-marly-delina-exclusif', 'delina-exclusif'],
            'brands' => ['Parfums de Marly'],
            'concentrations' => ['parfum', 'extrait'],
            'mode' => 'pyramid',
            'family' => 'Hoa cỏ · Hổ phách',
            'layers' => [
                'top' => ['label' => 'Hương đầu', 'notes' => ['Bergamot', 'Lê', 'Vải'], 'description' => 'Trái cây mọng nước mở ra sắc hương tươi.'],
                'heart' => ['label' => 'Hương giữa', 'notes' => ['Hoa hồng Damascena', 'Hương nhang'], 'description' => 'Hoa hồng sâu hơn nhờ sắc nhang trầm lắng.'],
                'base' => ['label' => 'Hương cuối', 'notes' => ['Vanilla', 'Xạ hương', 'Rêu', 'Đậu tonka'], 'description' => 'Nền hương mềm, ngọt ấm và ôm lấy hoa.'],
            ],
            'key_notes' => ['Vải', 'Hoa hồng Damascena', 'Hương nhang', 'Vanilla'],
            'moods' => ['velvet'],
            'mood_reason' => ['velvet' => 'Hoa hồng, hương nhang và vanilla tạo cảm giác sâu, ấm.'],
            'story' => 'Sắc vải và lê dẫn vào hoa hồng, rồi lắng trên vanilla và xạ hương. Nét hoa mềm có thêm chiều sâu của nhang.',
            'occasion' => 'Gợi ý Soopi: thử vào chiều tối hoặc tiết trời mát khi muốn một dấu hương hoa đậm hơn.',
            'sources' => [['label' => 'Parfums de Marly — Delina Exclusif', 'url' => 'https://us.parfums-de-marly.com/products/delina-exclusif']],
        ],
        'rose-prick-edp' => [
            'names' => ['Tom Ford Rose Prick Private Blend', 'Tom Ford Rose Prick Eau de Parfum', 'Tom Ford Rose Prick'],
            'slugs' => ['tom-ford-rose-prick-edp', 'tom-ford-rose-prick', 'tom-ford-rose-prick-eau-de-parfum'],
            'brands' => ['Tom Ford'],
            'concentrations' => ['edp'],
            'mode' => 'keynotes',
            'family' => 'Hoa hồng · Gia vị · Gỗ',
            'key_notes' => ['Hoa hồng Bulgaria', 'Chiết xuất nghệ', 'Hoắc hương Indonesia', 'Tiêu Tứ Xuyên', 'Đậu tonka rang', 'Nhựa thơm tolu'],
            'moods' => ['velvet'],
            'mood_reason' => ['velvet' => 'Hoa hồng gặp tiêu, hoắc hương và tonka ấm.'],
            'story' => 'Hoa hồng được đặt cạnh gia vị và sắc gỗ của hoắc hương. Tonka đem đến độ ấm, làm bó hoa có thêm nét cá tính.',
            'occasion' => 'Gợi ý Soopi: thử khi muốn một dấu hương hoa khác biệt, nhất là trong một buổi tối thân mật.',
            'sources' => [['label' => 'Tom Ford Beauty — Rose Prick Eau de Parfum', 'url' => 'https://www.tomfordbeauty.com/products/rose-prick-eau-de-parfum']],
        ],
        'musc-noir-rose-edp' => [
            'names' => ['Narciso Rodriguez Musc Noir Rose', 'Narciso Rodriguez For Her Musc Noir Rose', 'For Her Musc Noir Rose Eau de Parfum'],
            'slugs' => ['narciso-rodriguez-musc-noir-rose', 'narciso-rodriguez-for-her-musc-noir-rose', 'for-her-musc-noir-rose-eau-de-parfum'],
            'brands' => ['Narciso Rodriguez'],
            'concentrations' => ['edp'],
            'mode' => 'pyramid',
            'family' => 'Hoa huệ · Xạ hương · Vanilla',
            'layers' => [
                'top' => ['label' => 'Hương đầu', 'notes' => ['Bergamot Ý', 'Tiêu hồng'], 'description' => 'Cam chanh và tiêu hồng tạo nét sáng ban đầu.'],
                'heart' => ['label' => 'Hương giữa', 'notes' => ['Xạ hương'], 'description' => 'Trái tim xạ hương mang nét mềm đặc trưng của dòng for her.'],
                'base' => ['label' => 'Hương cuối', 'notes' => ['Vanilla', 'Hương da lộn', 'Hoắc hương Indonesia'], 'description' => 'Nền vanilla ấm, mềm với sắc da lộn và hoắc hương.'],
            ],
            'key_notes' => ['Bergamot', 'Hoa huệ', 'Xạ hương', 'Vanilla'],
            'moods' => ['velvet'],
            'mood_reason' => ['velvet' => 'Xạ hương và vanilla làm mềm nét hoa huệ nồng nàn.'],
            'story' => 'Hoa huệ, chút mận và trái tim xạ hương gặp nền vanilla. Hương thơm gợi một cảm giác mềm, ấm và gần gũi.',
            'occasion' => 'Gợi ý Soopi: thử cho buổi hẹn hoặc chiều tối; bắt đầu với lượng xịt nhẹ.',
            'sources' => [['label' => 'Narciso Rodriguez — for her Musc Noir Rose', 'url' => 'https://www.narcisorodriguezparfums.com/en/narciso-rodriguez-for-her-musc-noir-rose/for-her-MUSC-NOIR-ROSE.html']],
        ],
        'in-love-with-you-edp' => [
            'names' => ['In Love With You Eau de Parfum', 'Emporio Armani In Love With You', 'Emporio Armani In Love With You Eau de Parfum'],
            'slugs' => ['in-love-with-you-eau-de-parfum', 'emporio-armani-in-love-with-you', 'emporio-armani-in-love-with-you-eau-de-parfum'],
            'brands' => ['Emporio Armani', 'Giorgio Armani'],
            'concentrations' => ['edp'],
            'mode' => 'keynotes',
            'family' => 'Trái cây · Hoa cỏ · Hoắc hương',
            'key_notes' => ['Anh đào đen', 'Hoa nhài', 'Hoa hồng', 'Hoắc hương'],
            'moods' => ['velvet'],
            'mood_reason' => ['velvet' => 'Anh đào đen và hoắc hương thêm độ đậm cho nét hoa.'],
            'story' => 'Anh đào đen đem đến sắc ngọt đậm, bên cạnh hoa nhài và hoa hồng. Hoắc hương giúp dấu hương có thêm chiều sâu.',
            'occasion' => 'Gợi ý Soopi: thử cho một buổi hẹn khi bạn thích trái cây ngọt và hoa cỏ rõ nét.',
            'sources' => [['label' => 'Armani Beauty — In Love With You', 'url' => 'https://www.armanibeauty.sa/en/offers/last-chance/emporio-armani-in-love-with-you/ww-00179-arm.html']],
        ],
        'stronger-with-you-intensely-edp' => [
            'names' => ['Stronger With You Intensely', 'Emporio Armani Stronger With You Intensely', 'Stronger With You Intensely Eau de Parfum'],
            'slugs' => ['stronger-with-you-intensely', 'emporio-armani-stronger-with-you-intensely', 'stronger-with-you-intensely-eau-de-parfum'],
            'brands' => ['Emporio Armani', 'Giorgio Armani'],
            'concentrations' => ['edp'],
            'mode' => 'pyramid',
            'family' => 'Thảo mộc · Gỗ hổ phách · Vanilla',
            'layers' => [
                'top' => ['label' => 'Hương đầu', 'notes' => ['Tiêu hồng'], 'description' => 'Gia vị cay nhẹ mở đầu cho sắc hương ấm.'],
                'heart' => ['label' => 'Hương giữa', 'notes' => ['Oải hương', 'Xô thơm'], 'description' => 'Thảo mộc tạo khoảng thoáng giữa nền ngọt ấm.'],
                'base' => ['label' => 'Hương cuối', 'notes' => ['Gỗ hổ phách', 'Vanilla'], 'description' => 'Hương gỗ và vanilla làm dấu hương thêm đầy đặn.'],
            ],
            'key_notes' => ['Tiêu hồng', 'Oải hương', 'Gỗ hổ phách', 'Vanilla'],
            'moods' => ['velvet'],
            'mood_reason' => ['velvet' => 'Vanilla và gỗ hổ phách tạo nền ngọt ấm.'],
            'story' => 'Tiêu hồng mở lối cho oải hương và xô thơm. Khi sắc thảo mộc dịu lại, gỗ hổ phách và vanilla giữ nhịp ấm.',
            'occasion' => 'Gợi ý Soopi: thử trong thời tiết mát hoặc buổi tối nếu bạn thích hương ngọt ấm.',
            'sources' => [['label' => 'Armani Beauty — Stronger With You Intensely', 'url' => 'https://www.armanibeauty.co.uk/perfume/mens-perfumes/stronger-with-you/emporio-armani-stronger-with-you-intensely/ww-00180-arm.html']],
        ],
        'pera-granita-edt' => [
            'names' => ['Aqua Allegoria Pera Granita', 'Guerlain Aqua Allegoria Pera Granita'],
            'slugs' => ['aqua-allegoria-pera-granita', 'guerlain-aqua-allegoria-pera-granita'],
            'brands' => ['Guerlain'],
            'concentrations' => ['edt'],
            'mode' => 'keynotes',
            'family' => 'Trái cây · Cam chanh · Hoa mộc tê',
            'key_notes' => ['Lê', 'Bưởi', 'Chanh', 'Bergamot', 'Hoa mộc tê', 'Hương gỗ và xạ hương'],
            'moods' => ['sage', 'rose'],
            'mood_reason' => ['sage' => 'Lê, bưởi và chanh tạo cảm giác mọng nước, tươi sáng.', 'rose' => 'Hoa mộc tê thêm nét trái cây mềm trên nền gỗ, xạ hương.'],
            'story' => 'Lê mọng nước gặp vị tươi của bưởi và chanh. Hoa mộc tê thêm sắc quả mơ dịu ngọt trên nền gỗ, xạ hương.',
            'occasion' => 'Gợi ý Soopi: thử cho buổi sáng, đi dạo hoặc ngày muốn hương trái cây tươi nhẹ.',
            'sources' => [['label' => 'Guerlain — Aqua Allegoria Pera Granita', 'url' => 'https://www.guerlain.com/us/en-us/p/aqua-allegoria-pera-granita---eau-de-toilette-P014403.html']],
        ],
        'cr7-edt' => [
            'names' => ['Nước Hoa Cristiano Ronaldo CR7 EDT 100ml Chính Hãng', 'Cristiano Ronaldo CR7 Eau de Toilette', 'CR7 Eau de Toilette'],
            'slugs' => ['nuoc-hoa-cristiano-ronaldo-cr7-edt-100ml-chinh-hang', 'cristiano-ronaldo-cr7-eau-de-toilette', 'cr7-eau-de-toilette'],
            'brands' => ['Cristiano Ronaldo'],
            'concentrations' => ['edt'],
            'mode' => 'keynotes',
            'family' => 'Gỗ · Gia vị',
            'key_notes' => ['Bergamot', 'Bạch đậu khấu', 'Oải hương lai', 'Thuốc lá', 'Quế', 'Đàn hương', 'Xạ hương', 'Vanilla'],
            'moods' => ['velvet'],
            'mood_reason' => ['velvet' => 'Quế, thuốc lá và vanilla gợi sắc hương ấm.'],
            'story' => 'Cam chanh và oải hương gặp gia vị, thuốc lá và gỗ. Vanilla làm mềm tổng thể, đem lại nét ấm trong dấu hương.',
            'occasion' => 'Gợi ý Soopi: thử khi thích hương gỗ, gia vị cho những buổi gặp gỡ thường ngày.',
            'sources' => [['label' => 'CR7 Fragrances — CR7 Eau de Toilette', 'url' => 'https://cr7fragrances.store/collections/fragrances/products/cr7-eau-de-toilette']],
        ],
    ],
];
