@extends('gifts.layout')
@section('gift-content')
<article class="gx-reveal">
    @if($preview)<div class="gx-notice">{{ __('Bạn đang xem trước. Lượt xem này không được tính là người nhận đã mở quà.') }} <a href="{{ route('gifts.edit', $gift) }}">{{ __('Quay lại chỉnh sửa') }}</a></div>@endif
    <header class="gx-letter-heading"><span class="gx-kicker">JUST FOR YOU</span><p>{{ __('Gửi người thương mến,') }}</p><h1>{{ $gift->recipient_name }}</h1><span class="gx-letter-line" aria-hidden="true"></span></header>
    <div class="gx-letter"><div class="gx-letter-copy"><span class="gx-kicker">01 / {{ __('Một lời thương') }}</span><p class="gx-message">{{ $gift->message }}</p><p class="gx-signature">{{ __('Thân gửi từ,') }}<strong>{{ $gift->sender_name }}</strong></p></div>@if($gift->photo_path)<figure class="gx-memory-photo"><img src="{{ route('gifts.media', [$gift->token, 'photo']) }}" alt="{{ __('Ảnh kỷ niệm người tặng gửi bạn') }}" width="600" height="700"><figcaption>{{ __('Một khoảnh khắc muốn giữ cùng bạn.') }}</figcaption></figure>@endif</div>
    @if($gift->audio_path)<section class="gx-voice"><span class="gx-kicker">{{ __('Lắng nghe một chút thương') }}</span><h2>{{ __('Có những lời, muốn tự mình nói.') }}</h2><audio controls preload="none" src="{{ route('gifts.media', [$gift->token, 'audio']) }}">{{ __('Trình duyệt của bạn không hỗ trợ phát âm thanh.') }}</audio></section>@endif
    @if($gift->perfume)<section class="gx-fragrance"><img src="{{ $gift->perfume->image_src }}" alt="{{ $gift->perfume->localized_name }}" loading="lazy" referrerpolicy="no-referrer"><div><span class="gx-kicker">{{ __('Mùi hương đi cùng kỷ niệm') }}</span><h2>{{ $gift->perfume->localized_name }}</h2><p>{{ Str::limit(strip_tags($gift->perfume->localized_description), 700) }}</p></div></section>@endif
    @unless($preview)<section class="gx-thanks"><span class="gx-kicker">A NOTE BACK</span>@if($gift->thanked_at)<h2>{{ __('Lời cảm ơn đã được gửi.') }}</h2><p role="status">{{ __('Người tặng có thể đọc lời cảm ơn trong Quà của tôi.') }}</p>@else<h2>{{ __('Gửi lại một chút thương.') }}</h2><p>{{ __('Lời cảm ơn chỉ hiển thị cho người tặng. Bạn có thể gửi một lần cho trang quà này.') }}</p>@if($errors->any())<p role="alert">{{ $errors->first() }}</p>@endif<form method="POST" action="{{ route('gifts.thank', $gift->token) }}">@csrf<label for="gift-thanks">{{ __('Lời cảm ơn của bạn') }}</label><textarea id="gift-thanks" name="thank_you" rows="4" required minlength="3" maxlength="1000">{{ old('thank_you') }}</textarea><button class="gx-button" type="submit">{{ __('Gửi lời cảm ơn') }} <span aria-hidden="true">↗</span></button></form>@endif</section><form class="gx-close" method="POST" action="{{ route('gifts.lock', $gift->token) }}">@csrf<button type="submit">{{ __('Đóng và khóa lại món quà') }}</button></form>@endunless
</article>
@endsection
