@extends('layouts.store')

@section('title', __('Hộp Thử Mùi Tự Chọn (Discovery Box) · Trải Nghiệm 3-5 Mẫu Chiết | Soopi'))
@section('meta_description', __('Tuyển chọn hộp 3 hoặc 5 mẫu nước hoa, mỗi mẫu 5ml. Thử trên da trước khi chọn chai lớn; giá từ 199.000₫ một hộp.'))

@section('content')
<div class="store-container ht-discovery-page">
    @if($errors->any())
        <div class="public-flash alert-danger" role="alert">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>
    @endif
    <header class="ht-discovery-hero">
        <span class="ht-badge-pill">@include('partials.icon', ['name' => 'gift', 'size' => '1em']) {{ __('BỘ SƯU TẬP TRẢI NGHIỆM') }}</span>
        <h1 class="ht-discovery-title">{{ __('Thử một chút.') }}<br><em>{{ __('Yêu thật lâu.') }}</em></h1>
        <p class="ht-discovery-subtitle">{{ __('Chọn 3 hoặc 5 mùi hương, mỗi mẫu 5ml. Dành thời gian thử trên da trước khi tìm ra chai nước hoa dành cho bạn.') }}</p>
    </header>

    {{-- Package Switcher --}}
    <div class="ht-box-size-switcher">
        <button type="button" class="size-btn active" data-size="3" data-price="199000" aria-pressed="true">
            <strong>{{ __('Hộp 3 Mẫu Chiết') }}</strong>
            <span>{{ __('199.000₫ · 3 × 5ml') }}</span>
        </button>
        <button type="button" class="size-btn" data-size="5" data-price="299000" aria-pressed="false">
            <span class="hot-tag">{{ __('TIẾT KIỆM NHẤT') }}</span>
            <strong>{{ __('Hộp 5 Mẫu Chiết') }}</strong>
            <span>{{ __('299.000₫ · 5 × 5ml') }}</span>
        </button>
    </div>

    {{-- 3D Virtual Gift Box Preview --}}
    <div class="ht-virtual-box">
        <div class="box-lid-label">
            @include('partials.brand-logo', ['class' => 'discovery-brand-logo'])
            <span>DISCOVERY BOX</span>
        </div>
        <div class="box-slots-wrap" id="boxSlots">
            {{-- 3 or 5 slots generated by JS --}}
        </div>
        <div class="box-summary-bar">
            <div class="box-price-info">
                <span class="label">{{ __('Tổng giá trị Hộp Thử Mùi:') }}</span>
                <span class="price" id="boxPriceDisplay">199.000₫</span>
                <span class="extra-benefit">{{ __('Mỗi mẫu 5ml · Giá trọn hộp, chưa gồm vận chuyển') }}</span>
            </div>
            <form action="{{ route('cart.add-discovery-box') }}" method="POST" id="discoveryForm">
                @csrf
                <input type="hidden" name="size" id="inputBoxSize" value="3">
                <div id="hiddenInputsWrap"></div>
                <button type="submit" class="ht-button ht-button-primary" id="addBoxBtn" disabled>
                    {{ __('Vui lòng chọn đủ 3 mẫu để thêm vào giỏ') }}
                </button>
            </form>
        </div>
    </div>
    <p id="discovery-status" role="status" aria-live="polite">@if($unavailableSelectionCount > 0){{ $unavailableSelectionCount }} {{ __('mẫu đã hết hoặc không còn khả dụng. Các mẫu còn lại được giữ trong hộp để bạn chọn tiếp.') }}@endif</p>
    @if($sampleAvailability->filter(fn ($remaining) => $remaining > 0)->count() < 3)
        <p class="public-flash">{{ __('Hiện chưa đủ 3 mùi có mẫu 5ml để hoàn thiện hộp.') }} <a href="{{ config('storefront.zalo_url') }}" target="_blank" rel="noopener">{{ __('Hỏi Soopi về mẫu thử ↗') }}</a></p>
    @endif
    <noscript><p>{{ __('Hãy bật JavaScript để chọn và sắp xếp hộp thử, hoặc') }} <a href="{{ config('storefront.zalo_url') }}">{{ __('nhắn Soopi để được hỗ trợ') }}</a>.</p></noscript>

    {{-- Perfume Picker Catalog --}}
    <section class="ht-perfume-picker-section">
        <div class="picker-header">
            <div>
                <h2>{{ __('Tuyển chọn cho hộp hương của bạn') }}</h2>
                <p>{{ __('Bấm nút') }} <strong>{{ __('"+ Cho vào hộp"') }}</strong> {{ __('trên từng chai để lấp đầy các khay mẫu thử.') }}</p>
            </div>
            <div class="picker-filter">
                <button class="filter-tab active" data-filter="all">{{ __('Tất Cả') }}</button>
                <button class="filter-tab" data-filter="nu">{{ __('Nữ Tính') }}</button>
                <button class="filter-tab" data-filter="nam">{{ __('Nam Tính') }}</button>
                <button class="filter-tab" data-filter="unisex">Unisex</button>
            </div>
        </div>

        <div class="picker-grid" id="pickerGrid">
            @foreach($perfumes as $perfume)
            @php
                $available = $sampleAvailability[$perfume->id] ?? 0;
                $editorial = \App\Services\FragranceEditorialService::forPerfume($perfume);
            @endphp
            <div class="picker-card" data-gender="{{ $perfume->gender }}" data-id="{{ $perfume->id }}" data-name="{{ $perfume->localized_name }}" data-brand="{{ $perfume->brand }}" data-img="{{ $perfume->image_src ?: asset('images/perfume-default.jpg') }}" data-available="{{ $available }}">
                <div class="card-thumb">
                    <img src="{{ $perfume->image_src ?: asset('images/perfume-default.jpg') }}" alt="{{ $perfume->localized_name }}" loading="lazy">
                </div>
                <div class="card-details">
                    <span class="card-brand">{{ $perfume->brand }}</span>
                    <h3 class="card-name">{{ $perfume->localized_name }}</h3>
                    <p class="card-family">{{ __($perfume->category->localized_name ?? __('Nước hoa')) }} · {{ match($perfume->gender) { 'nu' => __('Nữ'), 'nam' => __('Nam'), 'unisex' => 'Unisex', default => $perfume->gender } }}</p>
                    <p class="card-note">@include('partials.icon', ['name' => 'flower', 'size' => '1em']) {{ $editorial['verified'] ? implode(' · ', array_slice($editorial['key_notes'], 0, 3)) : __('Nốt hương đang được đối chiếu.') }}</p>
                </div>
                <button type="button" class="ht-button ht-button-light select-sample-btn" data-id="{{ $perfume->id }}" aria-pressed="false" @disabled($available < 1)>
                    {{ $available < 1 ? ($perfume->getStockForVolume(5) > 0 ? __('Đã đủ trong giỏ') : __('Mẫu 5ml đang hết')) : __('+ Cho vào hộp') }}
                </button>
            </div>
            @endforeach
        </div>
    </section>
</div>

<style>
.ht-discovery-page {
    padding: 40px 20px 80px;
    max-width: 1100px;
    margin: 0 auto;
}
.ht-discovery-hero {
    text-align: center;
    margin-bottom: 30px;
}
.ht-discovery-title {
    font: 400 clamp(28px, 5vw, 42px) 'Playfair Display', 'Soopi Serif', Georgia, serif;
    color: #2b1f26;
    margin: 12px 0 10px;
}
.ht-discovery-title em {
    color: #c2476a;
    font-style: italic;
}
.ht-discovery-subtitle {
    color: #6d5b64;
    font-size: 16px;
    max-width: 720px;
    margin: 0 auto;
    line-height: 1.6;
}
.ht-box-size-switcher {
    display: flex;
    justify-content: center;
    gap: 16px;
    margin-bottom: 30px;
    flex-wrap: wrap;
}
.size-btn {
    border: 2px solid #f3d4e0;
    border-radius: 18px;
    padding: 18px 28px;
    background: #ffffff;
    cursor: pointer;
    text-align: center;
    min-width: 240px;
    position: relative;
    transition: all 0.25s ease;
}
.size-btn strong {
    display: block;
    font-size: 18px;
    color: #3b2832;
    margin-bottom: 4px;
}
.size-btn span {
    font-size: 13.5px;
    color: #8b6b7a;
}
.size-btn.active {
    border-color: #c2476a;
    background: #fff0f5;
    box-shadow: 0 10px 28px rgba(194, 71, 106, 0.18);
    transform: translateY(-2px);
}
.size-btn .hot-tag {
    position: absolute;
    top: -10px;
    right: 16px;
    background: #c2476a;
    color: #fff;
    font-size: 10px;
    font-weight: 700;
    padding: 3px 8px;
    border-radius: 10px;
}

/* Virtual Gift Box */
.ht-virtual-box {
    background: linear-gradient(135deg, #2b1b22, #4a2836);
    border-radius: 28px;
    padding: 32px 30px;
    color: #fff;
    box-shadow: 0 20px 50px rgba(74, 40, 54, 0.35);
    margin-bottom: 50px;
    border: 2px solid #87435f;
}
.box-lid-label {
    text-align: center;
    letter-spacing: 3px;
    font-size: 12px;
    color: #fbcfe8;
    margin-bottom: 24px;
    border-bottom: 1px dashed rgba(251, 207, 232, 0.2);
    padding-bottom: 12px;
}
.box-slots-wrap {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(170px, 1fr));
    gap: 16px;
    margin-bottom: 28px;
}
.box-slot {
    background: rgba(255, 255, 255, 0.08);
    border: 2px dashed rgba(251, 207, 232, 0.4);
    border-radius: 18px;
    padding: 20px 14px;
    text-align: center;
    min-height: 200px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    position: relative;
    transition: all 0.25s ease;
}
.box-slot.filled {
    background: rgba(255, 255, 255, 0.16);
    border: 2px solid #f472b6;
    box-shadow: 0 8px 24px rgba(244, 114, 182, 0.25);
}
.slot-vial-icon {
    font-size: 40px;
    margin-bottom: 10px;
    opacity: 0.5;
}
.slot-filled-img {
    width: 64px;
    height: 64px;
    object-fit: contain;
    margin-bottom: 10px;
}
.slot-brand {
    font-size: 10.5px;
    letter-spacing: 1px;
    color: #fbcfe8;
    text-transform: uppercase;
}
.slot-name {
    font-size: 13.5px;
    font-weight: 600;
    color: #fff;
    margin: 3px 0 10px;
    line-height: 1.25;
}
.remove-sample-btn {
    background: rgba(239, 68, 68, 0.2);
    border: 1px solid rgba(239, 68, 68, 0.5);
    color: #fca5a5;
    border-radius: 8px;
    padding: 3px 8px;
    font-size: 11px;
    cursor: pointer;
    transition: background 0.2s;
}
.remove-sample-btn:hover {
    background: rgba(239, 68, 68, 0.4);
    color: #fff;
}
.slot-empty-text {
    font-size: 13px;
    color: #e5b3c8;
}
.slot-empty-num {
    font-size: 11px;
    color: #a87990;
    margin-top: 4px;
}
.box-summary-bar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    border-top: 1px solid rgba(255, 255, 255, 0.15);
    padding-top: 20px;
    flex-wrap: wrap;
    gap: 16px;
}
.box-price-info .label {
    display: block;
    font-size: 13px;
    color: #fbcfe8;
}
.box-price-info .price {
    font-size: 28px;
    font-weight: 700;
    color: #fef08a;
    display: block;
}
.box-price-info .extra-benefit {
    font-size: 12px;
    color: #cbd5e1;
    display: block;
    margin-top: 3px;
}

/* Picker Catalog */
.ht-perfume-picker-section {
    margin-top: 20px;
}
.picker-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-end;
    margin-bottom: 24px;
    flex-wrap: wrap;
    gap: 16px;
}
.picker-header h2 {
    font: 600 24px var(--ht-serif);
    color: #2b1f26;
    margin: 0 0 6px;
}
.picker-header p {
    color: #715865;
    font-size: 14px;
    margin: 0;
}
.picker-filter {
    display: flex;
    gap: 8px;
}
.filter-tab {
    border: 1px solid #e5d3dc;
    background: #fff;
    color: #55444e;
    padding: 6px 14px;
    border-radius: 20px;
    font-size: 13px;
    cursor: pointer;
    transition: all 0.2s;
}
.filter-tab.active {
    background: #c2476a;
    border-color: #c2476a;
    color: #fff;
}
.picker-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));
    gap: 20px;
}
.picker-card {
    background: #fff;
    border: 1px solid #fce7f3;
    border-radius: 18px;
    padding: 18px;
    display: flex;
    flex-direction: column;
    box-shadow: 0 4px 16px rgba(0,0,0,0.03);
    transition: transform 0.2s, box-shadow 0.2s;
}
.picker-card:hover {
    transform: translateY(-3px);
    box-shadow: 0 10px 24px rgba(194, 71, 106, 0.1);
}
.card-thumb {
    text-align: center;
    background: #faf4f7;
    border-radius: 12px;
    padding: 12px;
    margin-bottom: 12px;
}
.card-thumb img {
    height: 110px;
    object-fit: contain;
}
.card-brand {
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 1px;
    color: #c2476a;
    font-weight: 700;
}
.card-name {
    font: 600 16px var(--ht-serif);
    color: #2b1f26;
    margin: 3px 0 4px;
}
.card-family {
    font-size: 12px;
    color: #8b7782;
    margin-bottom: 6px;
}
.card-note {
    font-size: 12px;
    color: #5e4b56;
    line-height: 1.4;
    margin-bottom: 14px;
    flex-grow: 1;
}
.select-sample-btn {
    width: 100%;
    font-weight: 600;
    text-align: center;
}
.select-sample-btn.selected {
    background: #2e7d32;
    color: #fff;
    border-color: #2e7d32;
}
</style>

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function () {
    let currentSize = {{ $initialSize }};
    let selectedSamples = {{ Illuminate\Support\Js::from($initialSamples) }};
    const sizeBtns = document.querySelectorAll('.size-btn');
    const boxSlots = document.getElementById('boxSlots');
    const priceDisplay = document.getElementById('boxPriceDisplay');
    const addBoxBtn = document.getElementById('addBoxBtn');
    const inputBoxSize = document.getElementById('inputBoxSize');
    const hiddenInputsWrap = document.getElementById('hiddenInputsWrap');
    const status = document.getElementById('discovery-status');
    const escapeMarkup = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;'}[char]));

    function renderBox() {
        boxSlots.innerHTML = '';
        for (let i = 0; i < currentSize; i++) {
            const sample = selectedSamples[i];
            const slot = document.createElement('div');
            slot.className = 'box-slot' + (sample ? ' filled' : '');

            if (sample) {
                slot.innerHTML = `
                    <img src="${escapeMarkup(sample.img)}" alt="${escapeMarkup(sample.name)}" class="slot-filled-img">
                    <span class="slot-brand">${escapeMarkup(sample.brand)}</span>
                    <strong class="slot-name">${escapeMarkup(sample.name)}</strong>
                    <button type="button" class="remove-sample-btn" data-index="${i}">@include('partials.icon', ['name' => 'close', 'size' => '1em']) ${window.soopiT('Đổi mùi khác')}</button>
                `;
            } else {
                slot.innerHTML = `
                    <div class="slot-vial-icon">@include('partials.icon', ['name' => 'vial', 'size' => '1em'])</div>
                    <span class="slot-empty-text">${(window.soopiT || (text => text))("+ Chọn mẫu")} ${i + 1}</span>
                    <span class="slot-empty-num">${(window.soopiT || (text => text))("Khe thử mùi số")} ${i + 1}</span>
                `;
            }
            boxSlots.appendChild(slot);
        }

        // Update hidden inputs for form
        hiddenInputsWrap.innerHTML = '';
        selectedSamples.forEach(s => {
            const inp = document.createElement('input');
            inp.type = 'hidden';
            inp.name = 'perfume_ids[]';
            inp.value = s.id;
            hiddenInputsWrap.appendChild(inp);
        });

        // Update add to cart button
        if (selectedSamples.length === currentSize) {
            addBoxBtn.disabled = false;
            addBoxBtn.textContent = `${(window.soopiT || (text => text))("Thêm Hộp")} ${currentSize} ${(window.soopiT || (text => text))("Mẫu Vào Giỏ Hàng (")}${currentSize === 5 ? '299.000₫' : '199.000₫'})`;
        } else {
            addBoxBtn.disabled = true;
            addBoxBtn.textContent = `${(window.soopiT || (text => text))("Vui lòng chọn thêm")} ${currentSize - selectedSamples.length} ${(window.soopiT || (text => text))("mẫu nữa")}`;
        }

        // Highlight selected buttons in picker
        document.querySelectorAll('.select-sample-btn').forEach(b => {
            if (b.disabled) return;
            const id = parseInt(b.dataset.id);
            const isSel = selectedSamples.some(s => s.id === id);
            b.classList.toggle('selected', isSel);
            b.setAttribute('aria-pressed', String(isSel));
            b.textContent = isSel ? (window.soopiT || (text => text))(" Đã chọn vào hộp") : (window.soopiT || (text => text))("+ Cho vào hộp");
        });
    }

    sizeBtns.forEach(btn => {
        btn.addEventListener('click', function () {
            sizeBtns.forEach(b => { b.classList.remove('active'); b.setAttribute('aria-pressed', 'false'); });
            this.classList.add('active');
            this.setAttribute('aria-pressed', 'true');
            currentSize = parseInt(this.dataset.size);
            priceDisplay.textContent = parseInt(this.dataset.price).toLocaleString('vi-VN') + '₫';
            inputBoxSize.value = currentSize;
            if (selectedSamples.length > currentSize) {
                selectedSamples = selectedSamples.slice(0, currentSize);
                status.textContent = (window.soopiT || (text => text))("Đã giữ 3 mùi đầu tiên theo thứ tự bạn chọn.");
            }
            renderBox();
        });
    });

    // Handle selecting perfume from catalog
    document.querySelectorAll('.select-sample-btn').forEach(btn => {
        btn.addEventListener('click', function () {
            if (this.disabled) return;
            const card = this.closest('.picker-card');
            const id = parseInt(card.dataset.id);
            const name = card.dataset.name;
            const brand = card.dataset.brand;
            const img = card.dataset.img;

            const existingIdx = selectedSamples.findIndex(s => s.id === id);
            if (existingIdx !== -1) {
                selectedSamples.splice(existingIdx, 1);
            } else {
                if (selectedSamples.length >= currentSize) {
                    status.textContent = currentSize === 3 ? (window.soopiT || (text => text))("Hộp đã đủ 3 mẫu. Hãy bỏ một mẫu hoặc chuyển sang hộp 5.") : (window.soopiT || (text => text))("Hộp đã đủ 5 mẫu. Hãy bỏ một mẫu để chọn mùi khác.");
                    return;
                }
                selectedSamples.push({ id, name, brand, img });
            }
            status.textContent = `${selectedSamples.length}/${currentSize} ${(window.soopiT || (text => text))("mẫu đã chọn.")}`;
            renderBox();
        });
    });

    // Handle removing sample from slot
    boxSlots.addEventListener('click', function (e) {
        const removeButton = e.target.closest('.remove-sample-btn');
        if (removeButton) {
            const idx = parseInt(removeButton.dataset.index);
            const removedId = selectedSamples[idx]?.id;
            selectedSamples.splice(idx, 1);
            status.textContent = `${selectedSamples.length}/${currentSize} ${(window.soopiT || (text => text))("mẫu đã chọn.")}`;
            renderBox();
            const pickerButton = [...document.querySelectorAll('.select-sample-btn')].find(button => Number(button.dataset.id) === removedId);
            if (pickerButton?.getClientRects().length) pickerButton.focus();
            else document.querySelector('.size-btn.active')?.focus();
        }
    });

    // Filter tabs
    document.querySelectorAll('.filter-tab').forEach(tab => {
        tab.addEventListener('click', function () {
            document.querySelectorAll('.filter-tab').forEach(t => t.classList.remove('active'));
            this.classList.add('active');
            const filter = this.dataset.filter;
            document.querySelectorAll('.picker-card').forEach(card => {
                if (filter === 'all' || card.dataset.gender === filter) {
                    card.style.display = 'flex';
                } else {
                    card.style.display = 'none';
                }
            });
        });
    });

    sizeBtns.forEach(button => {
        const active = Number(button.dataset.size) === currentSize;
        button.classList.toggle('active', active);
        button.setAttribute('aria-pressed', String(active));
    });
    priceDisplay.textContent = (currentSize === 5 ? 299000 : 199000).toLocaleString('vi-VN') + '₫';
    inputBoxSize.value = currentSize;
    renderBox();
});
</script>
@endpush
@endsection
