@php
    $mailCopy = match ($details['type']) {
        'paid' => ['THANH TOÁN ĐÃ ĐƯỢC GHI NHẬN', 'Một bước gần hơn.', 'Soopi đã ghi nhận thanh toán cho đơn hàng của bạn. Bạn có thể theo dõi quá trình chuẩn bị và giao hàng qua liên kết bên dưới.'],
        'dispatched' => ['CẬP NHẬT GIAO HÀNG', 'Mùi hương đang trên đường.', 'Đơn hàng của bạn đã được cập nhật sang giai đoạn vận chuyển. Xem tiến trình mới nhất trong trang theo dõi đơn hàng.'],
        'delivered' => ['ĐÃ CẬP NHẬT GIAO THÀNH CÔNG', 'Một mùi hương. Đã đến bên bạn.', 'Đơn hàng được cập nhật là đã giao thành công. Nếu bạn chưa nhận được hàng hoặc cần hỗ trợ, hãy liên hệ Soopi kèm mã đơn bên dưới.'],
        default => ['SOOPI ĐÃ NHẬN ĐƠN CỦA BẠN', 'Cảm ơn bạn đã chọn Soopi.', 'Mùi hương bạn chọn đã có một hành trình riêng. Soopi đã tiếp nhận đơn; thông tin thanh toán và giao hàng được ghi rõ bên dưới.'],
    };
    $money = fn ($amount) => number_format((float) $amount, 0, ',', '.').' ₫';
@endphp
<!DOCTYPE html>
<html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ $mailCopy[0] }} · {{ $details['order_number'] }}</title><style>td{overflow-wrap:break-word}@media only screen and (max-width:480px){.mail-inset{padding-left:20px!important;padding-right:20px!important}h1{font-size:30px!important}}</style></head>
<body style="margin:0;padding:0;background:#f4efec;color:#392632;font-family:Arial,Helvetica,sans-serif;-webkit-text-size-adjust:100%">
<div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent">{{ $mailCopy[0] }} · {{ $details['order_number'] }} · {{ $money($details['total']) }}</div>
<table role="presentation" style="width:100%;border-collapse:collapse"><tr><td align="center" style="padding:24px 12px">
<table role="presentation" style="width:100%;max-width:620px;border-collapse:collapse;background:#fffdfb;border:1px solid #e4d9de">
    <tr><td class="mail-inset" style="padding:28px 30px;border-bottom:1px solid #e4d9de"><a href="{{ url('/') }}" style="display:inline-block;text-decoration:none">@include('emails.partials.brand')</a></td></tr>
    @if($details['is_demo'])<tr><td class="mail-inset" style="padding:12px 30px;background:#fff3d9;color:#735127;font-size:12px">ĐƠN MÔ PHỎNG · Không phải xác nhận thu tiền hoặc giao hàng thật.</td></tr>@endif
    <tr><td class="mail-inset" style="padding:34px 30px 26px"><p style="margin:0 0 18px;font-size:10px;line-height:1.7;letter-spacing:1.5px;color:#896b7a">{{ $mailCopy[0] }}</p><h1 style="font:normal 34px/1.22 Georgia,'Times New Roman',serif;margin:0 0 23px;letter-spacing:-.6px">{{ $mailCopy[1] }}</h1><p style="font-size:14px;line-height:1.8;margin:0 0 12px">Chào {{ $details['customer_name'] }},</p><p style="font-size:14px;line-height:1.8;margin:0;color:#755e6b">{{ $mailCopy[2] }}</p></td></tr>
    <tr><td class="mail-inset" style="padding:0 30px 28px"><table role="presentation" style="border-collapse:collapse;width:100%;background:#f6eff2"><tr><td style="padding:18px;font-size:12px;line-height:1.8;color:#806371">MÃ ĐƠN HÀNG<strong style="display:block;font-size:21px;letter-spacing:.5px;color:#392632">{{ $details['order_number'] }}</strong></td><td align="right" style="padding:18px;font-size:12px;line-height:1.8;color:#806371">Ngày đặt<br><span style="color:#392632">{{ \Carbon\Carbon::parse($details['placed_at'])->timezone('Asia/Ho_Chi_Minh')->format('d/m/Y') }}</span></td></tr></table></td></tr>
    <tr><td class="mail-inset" style="padding:0 30px"><table style="width:100%;border-collapse:collapse;font-size:13px;line-height:1.6"><caption style="text-align:left;font:24px Georgia,'Times New Roman',serif;padding:0 0 16px">Những mùi hương bạn chọn</caption><thead><tr><th scope="col" align="left" style="padding:10px 0;border-bottom:1px solid #ddcfd6;color:#856b78;font-size:11px;font-weight:normal">SẢN PHẨM</th><th scope="col" align="right" style="padding:10px 0;border-bottom:1px solid #ddcfd6;color:#856b78;font-size:11px;font-weight:normal">THÀNH TIỀN</th></tr></thead><tbody>
        @foreach($details['items'] as $item)<tr><td style="padding:17px 14px 17px 0;border-bottom:1px solid #eee4e8"><strong style="font-weight:normal">{{ $item['name'] }}</strong><br><span style="font-size:12px;color:#856b78">{{ $item['volume_label'] ?? ($item['volume_ml'].' ml') }} · Số lượng {{ $item['quantity'] }}</span>@if(!empty($item['sample_names']))<br><span style="font-size:11px;color:#856b78">Mẫu 5ml: {{ implode(' · ', $item['sample_names']) }}</span>@endif</td><td align="right" style="padding:17px 0;border-bottom:1px solid #eee4e8;vertical-align:top;white-space:nowrap">{{ $money($item['line_total']) }}</td></tr>@endforeach
    </tbody></table></td></tr>
    <tr><td class="mail-inset" style="padding:22px 30px"><table role="presentation" style="width:100%;border-collapse:collapse;font-size:13px;line-height:1.8;color:#755e6b"><tr><td style="padding:4px 0">Tiền hàng</td><td align="right">{{ $money($details['subtotal']) }}</td></tr><tr><td style="padding:4px 0">Phí vận chuyển</td><td align="right">{{ $money($details['shipping_fee']) }}</td></tr>@if($details['discount_amount'] > 0)<tr><td style="padding:4px 0">Ưu đãi</td><td align="right">−{{ $money($details['discount_amount']) }}</td></tr>@endif @if($details['points_discount'] > 0)<tr><td style="padding:4px 0">Điểm thành viên</td><td align="right">−{{ $money($details['points_discount']) }}</td></tr>@endif<tr><td style="padding:16px 0 6px;border-top:1px solid #ddcfd6;font-size:16px;color:#392632">Tổng đơn hàng</td><td align="right" style="padding:16px 0 6px;border-top:1px solid #ddcfd6;font-size:21px;color:#392632">{{ $money($details['total']) }}</td></tr></table></td></tr>
    <tr><td class="mail-inset" style="padding:0 30px 28px;font-size:13px;line-height:1.8"><p style="margin:0 0 10px"><strong>Thanh toán:</strong> {{ $details['payment_method'] }}<br><span style="color:#755e6b">{{ $details['payment_status'] }}</span></p><p style="margin:0"><strong>Giao đến:</strong><br>{{ $details['shipping_address'] }}</p>@if($details['tracking_code'])<p style="margin:12px 0 0"><strong>Mã vận đơn:</strong> {{ $details['tracking_code'] }}</p>@endif</td></tr>
    @if(!empty($details['note']))<tr><td class="mail-inset" style="padding:0 30px 28px;font-size:13px;line-height:1.8"><strong>Ghi chú đơn hàng:</strong><p style="margin:6px 0 0;white-space:pre-line;overflow-wrap:anywhere">{{ $details['note'] }}</p></td></tr>@endif
    <tr><td class="mail-inset" align="center" style="padding:0 30px 30px"><table role="presentation" style="border-collapse:collapse;width:100%;background:#392632"><tr><td align="center" style="padding:17px 18px"><a href="{{ $details['tracking_url'] }}" style="display:block;color:#fff9f5;font-size:14px;text-decoration:none">Theo dõi đơn hàng →</a></td></tr></table><p style="font-size:11px;line-height:1.7;color:#856b78;margin:13px 0 0">Vui lòng đăng nhập tài khoản đặt hàng để xem thông tin chi tiết.</p></td></tr>
    <tr><td class="mail-inset" style="padding:25px 30px;background:#f6eff2;border-top:1px solid #e4d9de"><p style="font:italic 23px Georgia,'Times New Roman',serif;margin:0 0 12px;color:#805b71">Một chút hương. Một chút thương.</p><p style="font-size:12px;line-height:1.8;color:#755e6b;margin:0">Cần hỗ trợ? <a href="{{ config('storefront.zalo_url') }}" style="color:#392632">Zalo {{ config('storefront.zalo_phone') }}</a> · <a href="{{ route('store.contact') }}" style="color:#392632">Liên hệ Soopi</a></p><p style="font-size:11px;line-height:1.8;color:#856b78;margin:12px 0 0">Đây là thông báo giao dịch liên quan đến đơn hàng của bạn. <a href="{{ route('store.privacy') }}" style="color:#755e6b">Chính sách riêng tư</a></p></td></tr>
</table>
</td></tr></table></body></html>
