@extends('layouts.admin')
@section('title', __('Quản lý danh mục'))
@section('page_title', __('Danh mục sản phẩm'))
@section('content')
<div class="studio-function-metrics">
    @foreach([[__('Tổng danh mục'), $stats['total'], 'layer-group', __('Các nhóm sản phẩm trong cửa hàng')], [__('Có sản phẩm'), $stats['populated'], 'spray-can-sparkles', __('Đã phân loại ít nhất một sản phẩm')], [__('Chưa có sản phẩm'), $stats['empty'], 'folder-open', __('Có thể bổ sung sản phẩm hoặc sắp xếp lại')]] as [$label, $value, $icon, $note])
    <div class="studio-function-metric"><div><span>{{ __($label) }}</span><strong>{{ number_format($value) }}</strong><small>{{ $note }}</small></div><i class="fa-solid fa-{{ $icon }}" aria-hidden="true"></i></div>
    @endforeach
</div>
<section class="admin-card studio-directory">
    <form method="GET" action="{{ route('admin.categories.index') }}" class="studio-directory-filters"><div class="studio-search-field"><label for="category-search">{{ __('Tìm danh mục') }}</label><input id="category-search" name="search" type="search" class="form-control" value="{{ request('search') }}" maxlength="100" placeholder="{{ __('Nhập tên danh mục…') }}"></div><button type="submit" class="btn btn-primary"><i class="fa-solid fa-magnifying-glass mr-1" aria-hidden="true"></i> {{ __('Tìm kiếm') }}</button>@if(request()->filled('search'))<a href="{{ route('admin.categories.index') }}" class="btn btn-outline-secondary">{{ __('Xóa bộ lọc') }}</a>@endif</form>
    <div class="studio-list-heading"><h3>{{ __('Danh mục') }} <span>{{ number_format($categories->total()) }}</span></h3><small>{{ __('Phân loại & số lượng sản phẩm') }}</small></div>
    <div class="table-responsive"><table class="table table-hover table-admin mb-0"><thead><tr><th>{{ __('Danh mục') }}</th><th>{{ __('Sản phẩm') }}</th><th>{{ __('Ngày tạo') }}</th><th class="text-right">{{ __('Thao tác') }}</th></tr></thead><tbody>
        @forelse($categories as $category)
        <tr><td><a class="font-weight-bold" href="{{ route('admin.categories.show', $category) }}">{{ __($category->name) }}</a><small class="d-block text-muted mt-1">#{{ $category->id }}</small></td><td><span class="{{ $category->perfumes_count ? 'badge-active' : 'badge-inactive' }}">{{ number_format($category->perfumes_count) }} {{ __('sản phẩm') }}</span></td><td class="text-muted">{{ $category->created_at?->format('d/m/Y') ?? '—' }}</td><td><div class="studio-row-actions"><a href="{{ route('admin.categories.show', $category) }}" class="studio-icon-action" title="{{ __('Xem danh mục') }}" aria-label="Xem {{ __($category->name) }}"><i class="fa-regular fa-eye" aria-hidden="true"></i></a><a href="{{ route('admin.categories.edit', $category) }}" class="studio-icon-action" title="{{ __('Chỉnh sửa danh mục') }}" aria-label="Chỉnh sửa {{ __($category->name) }}"><i class="fa-regular fa-pen-to-square" aria-hidden="true"></i></a><form method="POST" action="{{ route('admin.categories.destroy', $category) }}" data-confirm="Xóa danh mục {{ __($category->name) }}? Các sản phẩm trong danh mục sẽ chuyển về trạng thái chưa phân loại.">@csrf @method('DELETE')<button type="submit" class="studio-icon-action studio-icon-action--danger" title="{{ __('Xóa danh mục') }}" aria-label="Xóa {{ __($category->name) }}"><i class="fa-regular fa-trash-can" aria-hidden="true"></i></button></form></div></td></tr>
        @empty<tr><td colspan="4"><div class="studio-directory-empty"><i class="fa-solid fa-layer-group" aria-hidden="true"></i><strong>{{ request()->filled('search') ? __('Không tìm thấy danh mục phù hợp') : __('Chưa có danh mục') }}</strong><p>{{ request()->filled('search') ? __('Thử một tên khác hoặc xóa bộ lọc.') : __('Tạo danh mục để sắp xếp bộ sưu tập và giúp khách hàng tìm sản phẩm.') }}</p><a class="btn btn-outline-secondary" href="{{ request()->filled('search') ? route('admin.categories.index') : route('admin.categories.create') }}">{{ request()->filled('search') ? __('Xóa bộ lọc') : __('Thêm danh mục đầu tiên') }}</a></div></td></tr>@endforelse
    </tbody></table></div>
    <div class="studio-list-footer"><span>{{ __('Hiển thị') }} {{ $categories->firstItem() ?? 0 }}–{{ $categories->lastItem() ?? 0 }} / {{ number_format($categories->total()) }} {{ __('danh mục') }}</span>{{ $categories->links() }}</div>
</section>
@endsection
