@extends('layouts.admin')
@section('title', __('Chi tiết danh mục'))
@section('page_title', __('Chi tiết danh mục'))
@section('content')
<div class="studio-list-heading mb-4"><div><span class="studio-form-kicker">{{ __('DANH MỤC #') }}{{ $category->id }}</span><h2>{{ __($category->name) }}</h2><p class="text-muted mb-0">{{ number_format($products->total()) }} {{ __('sản phẩm · Tạo ngày') }} {{ $category->created_at?->format('d/m/Y') ?? '—' }}</p></div><div><a href="{{ route('admin.categories.index') }}" class="btn btn-outline-secondary mr-2">{{ __('Danh sách') }}</a><a href="{{ route('admin.categories.edit', $category) }}" class="btn btn-primary"><i class="fa-regular fa-pen-to-square mr-1" aria-hidden="true"></i> {{ __('Chỉnh sửa') }}</a></div></div>
<section class="admin-card studio-directory"><div class="studio-list-heading"><h3>{{ __('Sản phẩm trong danh mục') }}</h3><a class="btn btn-outline-secondary btn-sm" href="{{ route('admin.products.create') }}">{{ __('Thêm sản phẩm') }}</a></div>
    <div class="table-responsive"><table class="table table-hover table-admin mb-0"><thead><tr><th>{{ __('Sản phẩm') }}</th><th>{{ __('Giá bán') }}</th><th>{{ __('Tồn kho') }}</th><th>{{ __('Trạng thái') }}</th><th class="text-right">{{ __('Thao tác') }}</th></tr></thead><tbody>
        @forelse($products as $product)<tr><td><a class="font-weight-bold" href="{{ route('admin.products.show', $product->id) }}">{{ $product->name }}</a><small class="d-block text-muted mt-1">#{{ $product->id }} · {{ $product->brand }}</small></td><td><strong>{{ number_format($product->sale_price ?? $product->price, 0, ',', '.') }}₫</strong>@if($product->sale_price !== null && $product->sale_price < $product->price)<del class="d-block small text-muted">{{ number_format($product->price, 0, ',', '.') }}₫</del>@endif</td><td><div class="small"><div>{{ __('Chai gốc') }} {{ $product->volume_ml }}ml: <strong>{{ $product->stock }}</strong></div><div class="text-muted">5ml: {{ $product->stock_5ml }} · 10ml: {{ $product->stock_10ml }} · 50ml: {{ $product->stock_50ml }}</div></div></td><td><span class="{{ $product->is_active ? 'badge-active' : 'badge-inactive' }}">{{ $product->is_active ? __('Đang mở bán') : __('Tạm ẩn') }}</span></td><td class="text-right"><a href="{{ route('admin.products.show', $product->id) }}" class="btn btn-outline-secondary btn-sm" aria-label="Xem {{ $product->name }}">{{ __('Chi tiết') }}</a></td></tr>
        @empty<tr><td colspan="5"><div class="studio-directory-empty"><i class="fa-solid fa-spray-can-sparkles" aria-hidden="true"></i><strong>{{ __('Danh mục chưa có sản phẩm') }}</strong><p>{{ __('Chọn danh mục này khi thêm hoặc chỉnh sửa một sản phẩm.') }}</p><a href="{{ route('admin.products.index') }}" class="btn btn-outline-secondary">{{ __('Mở danh sách sản phẩm') }}</a></div></td></tr>@endforelse
    </tbody></table></div>
    <div class="studio-list-footer"><span>{{ __('Hiển thị') }} {{ $products->firstItem() ?? 0 }}–{{ $products->lastItem() ?? 0 }} / {{ number_format($products->total()) }} {{ __('sản phẩm') }}</span>{{ $products->links() }}</div>
</section>
@endsection
